version: '3.8'
services:
  rabbitmq:
	container_name: "rabbitmq"  
	image: rabbitmq:3.8-management-alpine
	enviroment:
		- RABBITMQ_DEFAULT_USER=user
		- RABBITMQ_DEFAULT_PASS=mypass
	ports: 
    # RabbitMq Instanse
    - '5672:5672'
	# Web interfae
	- '15672:15672'